#!/bin/env bash
# Author: dmatosl <http://github.com/dmatosl>

source $PWD/exit_status_functions

# check given parameters
while getopts u:d:q:p: opts
do
    case "$opts" in
        u)  # check if user exists
            # check username length
            echo $OPTARG
            ;;
        d)  # check if domain exists
            echo $OPTARG
            ;;
        q)  #check if quota is enabled
            echo $OPTARG
            ;;
        p)  #check if password mask matches 
            #if password is empty generates random
            echo $OPTARG
            ;;
        [?])    echo  >&2 "Usage: $0 -u username -d domain.com -q quota -p password"
                exit 1
            ;;
    esac
done

# username 
if [ -z $user ] ; then
    script_exit missing_user
fi

# domain
if [ -z $domain ] ; then 
    script_exit missing_domain
fi

# quota
if [ -z $quota] ; then 
    script_exit missing_quota
fi

# password
if [ -z password ]; then
    script_exit missing_password
fi
