#!/bin/bash
# Author: dmatosl <http://github.com/dmatosl>

source $PWD/lib_validation
source $PWD/lib_exit_status

# check given parameters
while getopts u:d:q:p: opts
do
    case "$opts" in
        u)  # check if user exists
            if [[ $(user_exists $OPTARG) -eq 1 ]]; then
                script_exit user_exists
            fi
            # check valid user name 
            if [[ ! $(user_isvalid $OPTARG) -eq 1 ]]; then
                script_exit user_notvalid
            fi
            # check username length
            if [[ $(user_length) -eq 1 ]]; then
                script_exit user_length
            fi
            user=$OPTARG
            echo $user
            ;;
        d)  # check if domain exists
            domain=$OPTARG
            echo $domain
            ;;
        q)  #check if quota is enabled
            quota=$OPTARG
            echo $quota
            ;;
        p)  #check if password mask matches 
            #if password is empty generates random
            pass=$OPTARG
            echo $pass
            ;;
        [?])    echo  >&2 "Usage: $0 -u username -d domain.com -q quota -p password"
                exit 1
            ;;
    esac
done

# username 
if [ -z $user ] ; then
    script_exit missing_user
fi

# domain
if [ -z $domain ] ; then 
    script_exit missing_domain
fi

# quota
if [ -z $quota ] ; then 
    script_exit missing_quota
fi

# password
if [ -z $pass ] ; then
    script_exit missing_password
fi
