#!/bin/env bash
# Author: dmatosl <http://github.com/dmatosl>

function script_exit()
{
    case $1 in
        missing_user) 
            echo "[1:missing user:]"
            exit 1
        ;;
        missing_domain)
            echo "[2:missing domain:]"
            exit 2
        ;;
        missing_alias)
            echo "[3:missing alias:]"
            exit 3
        ;;
        missing_quota) 
            echo "[4:missing quota:]"
            exit 4
        ;;
        missing_password) 
            echo "[5:missing password:]"
            exit 5
        ;;

        [?])    echo "[-1:unknown:]"
                exit -1
        ;;
    esac
}
